name: Run tests and publish Allure 2 and 3 reports
run-name: Test and publish by ${{ github.actor }}

on:
  push:
    branches:
      - 'main'
  workflow_dispatch: {}

env:
  XCODE_VERSION: "16.2"

jobs:
  test:
    runs-on: macos-15
    steps:

      - name: Check Xcode version
        run: |
          xcode-select --print-path
          xcrun xcresulttool version
          sw_vers
