name: Run tests and publish Allure 2 and 3 reports
run-name: Test and publish by ${{ github.actor }}

on:
  push:
    branches:
      - 'main'
  workflow_dispatch: {}

env:
  XCODE_VERSION: "16.4"

jobs:
  test:
    runs-on: macos-15
    steps:
    
      - name: Set Xcode ${{ env.XCODE_VERSION }}
        run: |
          sudo xcode-select --switch /Applications/Xcode_${{ env.XCODE_VERSION }}.app

      - name: Check Xcode version
        run: |
          xcode-select --print-path
          xcrun xcresulttool version
          sw_vers
